# https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix
version: "3.8"
services:
  nginx:
    container_name: my-nginx-frontend
    depends_on:
      - backend
    restart: always # because it is routing traffic to our entire app
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - ${FRONTEND_PORT}:80
    volumes:
      # - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8.0
    restart: always
    container_name: my-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # - MYSQL_USER=root => root user created automatically
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    expose:
      - ${DB_PORT}
    volumes:
      - data:/var/lib/mysql

  backend:
    depends_on:
      - db
    restart: unless-stopped
    container_name: my-backend
    build:
      context: ./library-management-backend
    links:
      - db
    command: sh -c "npm run execSequelize && npm run build"
    environment:
      - DB_HOST=${DB_HOST}
    ports:
      - "${BACKEND_PORT}:8080"
volumes:
  data:

    # Run app with command: docker compose --env-file .env -p library-management up -d
